
package net.tecgurus.sistemabancario.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatalogoWS", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatalogoWS {


    /**
     * 
     * @param password
     * @param usuario
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.LoginResponse")
    @Action(input = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/loginRequest", output = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/loginResponse")
    public Boolean login(
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario);

    /**
     * 
     * @param noBancos
     * @return
     *     returns java.util.List<net.tecgurus.sistemabancario.ws.client.Banco>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBancosByExample", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.GetBancosByExample")
    @ResponseWrapper(localName = "getBancosByExampleResponse", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.GetBancosByExampleResponse")
    @Action(input = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/getBancosByExampleRequest", output = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/getBancosByExampleResponse")
    public List<Banco> getBancosByExample(
        @WebParam(name = "noBancos", targetNamespace = "")
        Integer noBancos);

    /**
     * 
     * @param noUsuarios
     * @return
     *     returns java.util.List<net.tecgurus.sistemabancario.ws.client.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsuariosByExample", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.GetUsuariosByExample")
    @ResponseWrapper(localName = "getUsuariosByExampleResponse", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", className = "net.tecgurus.sistemabancario.ws.client.GetUsuariosByExampleResponse")
    @Action(input = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/getUsuariosByExampleRequest", output = "http://webservices.sistemabancario_ws.tecgurus.net/CatalogoWS/getUsuariosByExampleResponse")
    public List<Usuario> getUsuariosByExample(
        @WebParam(name = "noUsuarios", targetNamespace = "")
        Integer noUsuarios);

}
