
package net.tecgurus.sistemabancario.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatalogoWSService", targetNamespace = "http://webservices.sistemabancario_ws.tecgurus.net/", wsdlLocation = "http://localhost:8080/sistemabancario-ws/catalogoWS?wsdl")
public class CatalogoWSService
    extends Service
{

    private final static URL CATALOGOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATALOGOWSSERVICE_EXCEPTION;
    private final static QName CATALOGOWSSERVICE_QNAME = new QName("http://webservices.sistemabancario_ws.tecgurus.net/", "CatalogoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sistemabancario-ws/catalogoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGOWSSERVICE_WSDL_LOCATION = url;
        CATALOGOWSSERVICE_EXCEPTION = e;
    }

    public CatalogoWSService() {
        super(__getWsdlLocation(), CATALOGOWSSERVICE_QNAME);
    }

    public CatalogoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGOWSSERVICE_QNAME, features);
    }

    public CatalogoWSService(URL wsdlLocation) {
        super(wsdlLocation, CATALOGOWSSERVICE_QNAME);
    }

    public CatalogoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGOWSSERVICE_QNAME, features);
    }

    public CatalogoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatalogoWS
     */
    @WebEndpoint(name = "CatalogoWSPort")
    public CatalogoWS getCatalogoWSPort() {
        return super.getPort(new QName("http://webservices.sistemabancario_ws.tecgurus.net/", "CatalogoWSPort"), CatalogoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogoWS
     */
    @WebEndpoint(name = "CatalogoWSPort")
    public CatalogoWS getCatalogoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.sistemabancario_ws.tecgurus.net/", "CatalogoWSPort"), CatalogoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGOWSSERVICE_EXCEPTION!= null) {
            throw CATALOGOWSSERVICE_EXCEPTION;
        }
        return CATALOGOWSSERVICE_WSDL_LOCATION;
    }

}
